#!/bin/sh


if [ "$(ping -c 1 -W 1 20.0.0.1 2>&1 | grep '100% packet loss')" != "" ] ; then 
	/bin/wifi
	echo . >> /tmp/offline
else
	echo . >  /tmp/offline
fi

if [ "$(cat /tmp/offline | wc -l)" -gt 5 ] ; then 
	reboot
fi
